pattern_name: exposure_to_environmental_condition
pattern_iri: http://purl.obolibrary.org/obo/ecto/patterns/exposure_to_environmental_condition.yaml

description: "exposures to an environmental condition"

contributors:
  - https://orcid.org/0000-0002-2908-3327

classes:
  exposure event: ExO:0000002
  environmental condition: ENVO:01000203

relations:
  has exposure stimulus: RO:0002309

annotationProperties:
  exact_synonym: oio:hasExactSynonym

vars:
  stressor: "'environmental condition'"

name:
  text: "exposure to %s"
  vars:
    - stressor

annotations:
  - annotationProperty: exact_synonym
    text: "%s exposure"
    vars:
      - stressor

def:
  text: "A exposure event involving the interaction of an exposure receptor to the condition of %s."
  vars:
    - stressor

equivalentTo:
  text: "'exposure event' and 'has exposure stimulus' some %s"
  vars:
    - stressor
